# Fazendo um percepton de uma camada usando lowlevel api:

### Utilizaremos a tabela verdade de um AND:

In [2]:
import numpy as np

In [2]:
X = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [3]:
y = np.array([[0.0], [0.0], [0.0], [1.0]])
y

array([[0.],
       [0.],
       [0.],
       [1.]])

In [4]:
W= np.array([[0.0],[0.0]])
W

array([[0.],
       [0.]])

In [5]:
def step(x):
    return float(x>=1)

In [6]:
camada_saida=np.matmul(X,W)
camada_saida

array([[0.],
       [0.],
       [0.],
       [0.]])

In [7]:
camada_de_saida_ativacao=np.array(list(map(step,camada_saida)))

camada_de_saida_ativacao=np.array([camada_de_saida_ativacao]).T  #transpondo o vetor linha para coluna

camada_de_saida_ativacao

array([[0.],
       [0.],
       [0.],
       [0.]])

In [8]:
erro = y-camada_de_saida_ativacao
erro

array([[0.],
       [0.],
       [0.],
       [1.]])

In [9]:
delta = np.matmul(X.T,erro)
delta

array([[1.],
       [1.]])

In [10]:
W=W+(0.1*delta)
W

array([[0.1],
       [0.1]])

In [11]:
erro_soma = np.sum(erro)
erro_soma

1.0

Fazendo a recorrencia do modelo:

In [12]:
del erro_soma, delta, camada_saida, erro, camada_de_saida_ativacao 
#limpando as variaveis
#rode as 3 celulas iniciais setando X, Y e W, antes de rodar a celula abaixo

In [13]:
epoca = 0
for i in range(20):
    epoca += 1
    
    camada_saida=np.matmul(X,W)
    
    camada_de_saida_ativacao=np.array(list(map(step,camada_saida)))
    camada_de_saida_ativacao=np.array([camada_de_saida_ativacao]).T  #transpondo o vetor linha para coluna
    
    erro = y-camada_de_saida_ativacao
    erro_soma = np.sum(erro)

    delta = np.matmul(X.T,erro)
    
    W=W+(0.1*delta)
        
    print('Época:', epoca, ' Erro: ', erro_soma)
    if erro_soma == 0.0:
        break

Época: 1  Erro:  1.0
Época: 2  Erro:  1.0
Época: 3  Erro:  1.0
Época: 4  Erro:  1.0
Época: 5  Erro:  0.0


# Fazendo um percepton com camada oculta: (lowlevel)

### Utilizaremos a tabela verdade da XOR:
Esse é um tipico problema linearmente não separavel

In [237]:
import random
from sklearn.metrics import mean_squared_error



In [3]:
X = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [6]:
y = np.array([[1.0], [0.0], [0.0], [1.0]])
y

array([[1.],
       [0.],
       [0.],
       [1.]])

In [7]:
neuronios_entrada = 2
neuronios_oculta = 3
neuronios_saida = 1

In [184]:
random.uniform(0,1)

0.7787907538237661

In [211]:
def cria_matriz_random(linha, coluna):
    lista_aux=[]
    for i in range(linha):
        for j in range(coluna):
            lista_aux.append(random.uniform(0,1))

    lista_aux=np.asarray(lista_aux)
    return lista_aux.reshape(linha, coluna)

Criei a funçao acima para facilitar na implementação dos dicionarios.

In [217]:
W = {'oculta': cria_matriz_random(neuronios_entrada,neuronios_oculta), 
     'saida': cria_matriz_random(neuronios_oculta,neuronios_saida)}
#basicamente esse é o dicionario com os pesos da rede

In [220]:
W

{'oculta': array([[0.43621627, 0.55054243, 0.84610644],
        [0.6839903 , 0.71208261, 0.38987006]]),
 'saida': array([[0.79248923],
        [0.94776903],
        [0.19656671]])}

In [221]:
b= {'oculta': cria_matriz_random(1,neuronios_oculta),
    'saida': cria_matriz_random(1,neuronios_saida)}
#basicamente esse é o dicionario com os pesos das Bias

In [222]:
b

{'oculta': array([[0.5429602 , 0.56044099, 0.08585243]]),
 'saida': array([[0.58575899]])}

Iremos utilizar a função sigmoide para ativação do neuronio.

In [230]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [254]:
#estamos calculando a saida através da entrada passando pelos pesos e ativaçao
taxa_aprendizagem=0.2

for i in range(1000):
    camada_oculta=np.matmul(X,W['oculta'])+b['oculta'] 
    camada_oculta_ativacao=sigmoid(camada_oculta)

    camada_saida=np.matmul(camada_oculta_ativacao,W['saida'])+b['saida']
    camada_saida_ativacao=sigmoid(camada_saida)

    erro=mean_squared_error(y, camada_saida_ativacao)

    #implementacao do backpropagantion
    #atualizando os pesos
    W['saida']=np.matmul(camada_oculta.T, camada_saida_ativacao)*taxa_aprendizagem*erro
    W['oculta']=np.matmul(X.T,camada_oculta_ativacao)*taxa_aprendizagem*erro
    #print('Erro:',erro)
    #print('Saidas:',camada_saida_ativacao)
    